### ISSUE TITLE
Where to download v1 data files

### ISSUE THREAD

**Issue by hungngocphat01** [vietai/SAT#10]
Hello,

Since v2 dataset files have not yet been available at the moment, I'm wondering where can I get download the v1 dataset files? It seems that all files within the GCS bucket cannot be downloaded (I get 403 forbidden every time).

Thank you and best regards.

**Comment by kocoten1992** [comment]
Hi @ntkchinh , @heraclex12 , @justinphan3110 , @lmthang , @thtrieu 

Currently v1 dataset cannot be downloaded, it have permission issue (403 forbidden), could you help us? Also do we have estimation time for v2 - looking forward to it :smiley:?

**Comment by heraclex12** [comment]
Hi @kocoten1992 and @hungngocphat01

There is a fork of MTet dataset in Huggingface, you can access our dataset from [here](https://huggingface.co/datasets/phongmt184172/mtet)

**Comment by WandererGuy** [comment]
from https://huggingface.co/datasets/phongmt184172/mtet, I have deduplicate Vietnamese sentence from mTet and save result in ALL_mtet.txt here, enjoy https://huggingface.co/datasets/WandererGuy/MTet/tree/main
