### ISSUE TITLE
Question about loading model

### ISSUE THREAD

**Issue by hieunguyenquoc** [vietai/SAT#4]
I have a question about loading model. I have trained a Russian-to-Vietnamese model base on your code and tensor2tensor. Every time I want to predict a new sentence, it always load the model again, even before that I have already predicted another sentence. I want to ask that if there is a way not to have reload the model when predict a new sentence. Thank you very much

**Comment by Mingg2211** [comment]
same problem, how can I load the pretrained model first and then make a predict
