### ISSUE TITLE
Where can I get v2 training data

### ISSUE THREAD

**Issue by moneyDboat** [vietai/SAT#6]
I haven't find v2 training data in the link provided
<img width="839" alt="image" src="https://user-images.githubusercontent.com/11391316/196920211-959b09d8-87c6-4bf9-b52f-f2263da8a182.png">

**Comment by heraclex12** [comment]
Hi @moneyDboat,

Sorry for the late response. The training data will be released soon after we fulfill all necessary requirements (i.g., licenses)
